### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by 107Steps** [ctrl-alt-d/lightpmmlpredictor#1]
When I tried to apply lightpmmlpredictor I found this error:
### script begins

import pandas as pd
from lightpredictor import utils

train = pd.read_csv('P:\python_sample\lightpmmlpredictor-master\sample-data\cd.csv')

pmml_scr = utils.predict('P:\python_sample\lightpmmlpredictor-master\pmml-models\dt.pmml', train)
### log begins

pmml_scr = utils.predict('P:\python_sample\lightpmmlpredictor-master\pmml-models\dt.pmml', train)
Traceback (most recent call last):

  File "<ipython-input-14-c3b6c1ce23bc>", line 1, in <module>
    pmml_scr = utils.predict('P:\python_sample\lightpmmlpredictor-master\pmml-models\dt.pmml', train)

  File "P:\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\lightpredictor\utils.py", line 15, in predict
    return predictTreeModel( model, values )

  File "P:\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\lightpredictor\utils.py", line 41, in predictTreeModel
    fill = next( e for e in Node

  File "P:\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\lightpredictor\utils.py", line 43, in <genexpr>
    unicode(values[ e[0].get('field') ]) == e[0].get('value')  )

NameError: name 'unicode' is not defined
### log ends

Any help would be appreciated!

**Comment by ctrl-alt-d** [comment]
Hi 107Steps,

it looks you are using Python 3, nice. Take a look:

http://stackoverflow.com/a/19877309/842935

please, when it runs for you, post a pull request to this repository in order to to be up to date and help other coders.

regards.

**Comment by 107Steps** [comment]
@ctrl-alt-d thanks for your guidance!

I simply coverted util.py via lib2to3 tools and it worked out perfectly.

just run command: 2to3 -w util.py and it will covert to suitable code for python 3 and create a org copy as well.
